### PR TITLE
Fixed #75: Attempt to resolve vite internals as deno package

### LINKED ISSUE #75: Cannot read properties of undefined (reading '0')
```
error during build:
[deno] Cannot read properties of undefined (reading '0')
    at resolveDeno (file:///C:/dev/project/node_modules/.deno/@deno+vite-plugin@1.0.5/node_modules/@deno/vite-plugin/dist/resolver.js:41:32)
    at Object.runMicrotasks (ext:core/01_core.js:692:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:59:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:76:3)
    at eventLoopTick (ext:core/01_core.js:185:21)
    at async resolveViteSpecifier (file:///C:/dev/project/node_modules/.deno/@deno+vite-plugin@1.0.5/node_modules/@deno/vite-plugin/dist/resolver.js:102:39)       
    at async Object.resolveId (file:///C:/dev/project/node_modules/.deno/@deno+vite-plugin@1.0.5/node_modules/@deno/vite-plugin/dist/resolvePlugin.js:18:20)       
    at async PluginDriver.hookFirstAndGetPlugin (file:///C:/dev/project/node_modules/.deno/rollup@4.46.2/node_modules/rollup/dist/es/shared/node-entry.js:22233:28)    at async resolveId (file:///C:/dev/project/node_modules/.deno/rollup@4.46.2/node_modules/rollup/dist/es/shared/node-entry.js:20714:26)
    at async ModuleLoader.resolveId (file:///C:/dev/project/node_modules/.deno/rollup@4.46.2/node_modules/rollup/dist/es/shared/node-entry.js:21150:15)
```

Steps to reproduce:

- Use Deno 2.4.2
- Create a react vite app with create-vite-extra and add tanstack router to the stack and use autoCodeSplitting
- Edit: You can also use the native react lazy code splitting function, same behavior
- Build the app

My deno.json
```
{
  "tasks": {
    "dev": "deno run -A --node-modules-dir npm:vite --host",
    "build": "deno run -A --node-modules-dir npm:vite build",
    "preview": "deno run -A --node-modules-dir npm:vite preview",
    "serve": "deno run --allow-net --allow-read jsr:@std/http@1/file-server dist/"
  },
  "compilerOptions": {
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "jsx": "react-jsx",
    "jsxImportSource": "react",
    "jsxImportSourceTypes": "@types/react"
  },
  "imports": {
    "@/": "./src/",
    "@deno/vite-plugin": "npm:@deno/vite-plugin@^1.0.5",
    "@hookform/resolvers": "npm:@hookform/resolvers@^5.2.0",
    "@radix-ui/react-avatar": "npm:@radix-ui/react-avatar@^1.1.10",
    "@radix-ui/react-dropdown-menu": "npm:@radix-ui/react-dropdown-menu@^2.1.15",
    "@radix-ui/react-label": "npm:@radix-ui/react-label@^2.1.7",
    "@radix-ui/react-slot": "npm:@radix-ui/react-slot@^1.2.3",
    "@tailwindcss/vite": "npm:@tailwindcss/vite@^4.1.11",
    "@tanstack/react-query": "npm:@tanstack/react-query@^5.83.0",
    "@tanstack/react-router": "npm:@tanstack/react-router@^1.130.8",
    "@tanstack/router-plugin": "npm:@tanstack/router-plugin@^1.130.8",
    "@types/react": "npm:@types/react@^19.1.8",
    "@types/react-dom": "npm:@types/react-dom@^19.1.6",
    "@vitejs/plugin-react-swc": "npm:@vitejs/plugin-react-swc@^3.10.2",
    "class-variance-authority": "npm:class-variance-authority@^0.7.1",
    "clsx": "npm:clsx@^2.1.1",
    "input-otp": "npm:input-otp@^1.4.2",
    "lucide-react": "npm:lucide-react@^0.525.0",
    "react": "npm:react@^19.1.0",
    "react-dom": "npm:react-dom@^19.1.0",
    "react-error-boundary": "npm:react-error-boundary@^6.0.0",
    "react-hook-form": "npm:react-hook-form@^7.61.1",
    "react-hot-toast": "npm:react-hot-toast@^2.5.2",
    "react-qr-code": "npm:react-qr-code@^2.0.18",
    "react-router-dom": "npm:react-router-dom@^7.7.0",
    "tailwind-merge": "npm:tailwind-merge@^3.3.1",
    "tailwindcss": "npm:tailwindcss@^4.1.11",
    "tw-animate-css": "npm:tw-animate-css@^1.3.6",
    "vite": "npm:vite@^7.0.0"
  }
}
```

Temporary fix:
- Downgrade to a lower version then 2.3.6 so something like 2.3.5, or 2.3.4 so im guessing the bug got introduced in the update 2.3.6

### PR DESCRIPTION
**Pull request by AjaniBilby**
Ideally someone else should test this, but I don't see how this one line change could create any unexpected issues.

Also I feel like this resolution shouldn't even be given to this plugin, I will raise an issue in vite as well

### CODE REVIEW

**Comment by AjaniBilby** [comment]
@marvinhagemeister is there any chance you could review or delegate this one line change before next week?

Weighting up the cost of waiting vs forcing in a patch in prod.

Thank you

File: src/resolver.ts [hunk 1]
```diff
@@ -71,6 +71,8 @@ export async function resolveDeno(
   id: string,
   cwd: string,
 ): Promise<DenoResolveResult | null> {
+  if (id.startsWith("\x00")) return null; // ignore vite virtual modules
```
Comment (swcarter007) [inline src/resolver.ts:74]: I tested this locally, but added a bit more just to ensure it was only targetting virtual modules.

```typescript 
if (id.startsWith("\x00virtual:"))
        return null;
```

It's up to you if you want to target the more specific syntax or not, but either way it worked properly for me and HMR started working again for me locally.

**Review by swcarter007 — APPROVED** [review]
The changes worked properly for me, and the suggestion is optional, and I'm good with either way.
